### ISSUE TITLE
prettier error occurred when use schema in jest

### ISSUE THREAD

**Issue by aya-eiya** [aya-eiya/nenux-gql-prettier-error#1]
When I refer to a schema object created by createSchema with prettier config from jest, I get a prettier error.

how to regenerate error & error:
```
> yarn test
yarn run v1.22.10
$ jest
 PASS  tests/jest.test.ts
  ref schema
    ✓ access schema variable

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.557 s, estimated 1 s
Ran all test suites.

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From tests/jest.test.ts.

      at Object.get graphql [as graphql] (node_modules/prettier/index.js:53298:12)
      at resolveParser$1 (node_modules/prettier/index.js:12937:21)
      at normalize$1 (node_modules/prettier/index.js:13048:18)
      at formatWithCursor$1 (node_modules/prettier/index.js:14746:46)
      at node_modules/prettier/index.js:60959:12
  console.error
    TypeError: Cannot read property 'graphql' of undefined
        at Object.get graphql [as graphql] (/Users/aya-eiya/Work/nenux-gql-prettier-error/node_modules/prettier/index.js:53298:50)
        at resolveParser$1 (/Users/aya-eiya/Work/nenux-gql-prettier-error/node_modules/prettier/index.js:12937:21)
        at normalize$1 (/Users/aya-eiya/Work/nenux-gql-prettier-error/node_modules/prettier/index.js:13048:18)
        at formatWithCursor$1 (/Users/aya-eiya/Work/nenux-gql-prettier-error/node_modules/prettier/index.js:14746:46)
        at /Users/aya-eiya/Work/nenux-gql-prettier-error/node_modules/prettier/index.js:60959:12
        at Object.format (/Users/aya-eiya/Work/nenux-gql-prettier-error/node_modules/prettier/index.js:60979:12)
        at /Users/aya-eiya/Work/nenux-gql-prettier-error/node_modules/nexus/src/typegenFormatPrettier.ts:40:21
        at Generator.next (<anonymous>)
        at fulfilled (/Users/aya-eiya/Work/nenux-gql-prettier-error/node_modules/tslib/tslib.js:114:62)

      at node_modules/nexus/src/makeSchema.ts:43:17

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

versions:
```
  "dependencies": {
    "graphql": "^15.8.0",
    "nexus": "^1.2.0"
  },
  "devDependencies": {
    "@types/jest": "^27.4.0",
    "@types/node": "^14.18.10",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-jest": "^26.0.0",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint": "^8.8.0",
    "jest": "^27.4.7",
    "prettier": "^2.5.1",
    "ts-jest": "^27.1.3",
    "typescript": "^4.5.5"
  }
```

**Comment by aya-eiya** [comment]
solved:

https://github.com/graphql-nexus/nexus/issues/1052
